from enum import Enum


class Environment(str, Enum):
    PRODUCTION = "production"
    TEST = "test"


class Capability(str, Enum):
    PHP_AVAILABLE = "PHP_AVAILABLE"
    WP_CONFIG_VALID = "WP_CONFIG_VALID"
    DATABASE_AVAILABLE = "DATABASE_AVAILABLE"
    WPCLI_AVAILABLE = "WPCLI_AVAILABLE"
    WP_CORE_DETECTED = "WP_CORE_DETECTED"
    WPCLI_PRE_BOOTSTRAP = "WPCLI_PRE_BOOTSTRAP"
    WPCLI_REDUCED_BOOTSTRAP = "WPCLI_REDUCED_BOOTSTRAP"
    WPCLI_FULL_BOOTSTRAP = "WPCLI_FULL_BOOTSTRAP"
    MULTISITE = "MULTISITE"


class HealthStatus(str, Enum):
    HEALTHY = "HEALTHY"
    PLUGIN_OR_THEME_CONFLICT = "PLUGIN_OR_THEME_CONFLICT"
    WPCLI_PARTIAL = "WPCLI_PARTIAL"
    PRE_BOOTSTRAP_RECOVERY_REQUIRED = "PRE_BOOTSTRAP_RECOVERY_REQUIRED"
    PHP_CONFIG_ERROR = "PHP_CONFIG_ERROR"
    DATABASE_UNAVAILABLE = "DATABASE_UNAVAILABLE"
    CORE_INCOMPLETE = "CORE_INCOMPLETE"
    UNKNOWN = "UNKNOWN"


class StepStatus(str, Enum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    SKIPPED = "SKIPPED"
    PLANNED = "PLANNED"


class RunStatus(str, Enum):
    PLANNED = "PLANNED"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    UPDATE_FAILED_PRESERVED = "UPDATE_FAILED_PRESERVED"
    PAUSED_FOR_MANUAL_REPAIR = "PAUSED_FOR_MANUAL_REPAIR"
    INCONSISTENT_AFTER_INTERVENTION = "INCONSISTENT_AFTER_INTERVENTION"


class Operation(str, Enum):
    MIGRATE = "migrate"
    UPDATE = "update"
    PIPELINE = "pipeline"
    RESUME = "resume"
    DIAGNOSE = "diagnose"
    INVENTORY = "inventory"
    PLAN = "plan"


class PendingOperationType(str, Enum):
    SEARCH_REPLACE = "SEARCH_REPLACE"


class WidgetEventType(str, Enum):
    WIDGET_OPTION_ADDED = "WIDGET_OPTION_ADDED"
    WIDGET_OPTION_REMOVED = "WIDGET_OPTION_REMOVED"
    WIDGET_OPTION_CHANGED = "WIDGET_OPTION_CHANGED"
    SIDEBAR_MAPPING_CHANGED = "SIDEBAR_MAPPING_CHANGED"


class DatabaseLocationStatus(str, Enum):
    FOUND = "FOUND"
    NOT_FOUND = "NOT_FOUND"
    AMBIGUOUS_DATABASE = "AMBIGUOUS_DATABASE"
